config/routes.rb
Rails.application.routes.draw do
  resources :menus
  root 'home#main'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'home/main'
  
  post 'main/custom' => 'home#complete_custom_quest'
  post 'main/daily' => 'home#complete_daily_quest'
  post 'main/party' => 'home#complete_party_quest'
  
  
  post 'main/new_quest' => 'home#new_quest'
  
  post 'map/move_island'=> 'home#move_island'
  
  post 'bag_item/wearing' => 'home#wearing_item'
  
  post 'pet/seleting' => 'home#selecting_pet'
  post 'pet/releasing' => 'home#releasing_pet'
  
  post 'shop/buy_pet' => 'home#buy_pet'
  post 'shop/buy_hat' => 'home#buy_hat'
  post 'shop/buy_clothes' => 'home#buy_clothes'
  post 'shop/buy_bag' => 'home#buy_bag'
  post 'shop/buy_ticket' => 'home#buy_ticket'
  
  
  post 'main/change_title' => 'home#change_title'
  
  get 'etc/rank'
  
  get 'etc/friend'
  post 'etc/friend/request' => 'etc#friend_request' # 새로운 친구 요청
  post 'etc/friend/accept' => 'etc#friend_accept' # 새로운 친구 요청
  
  
  get 'etc/main' => 'home#main'
  get 'etc/bag_item' => 'home#bag_item'
  get 'etc/map' => 'home#map'
  get 'etc/pet' => 'home#pet'
  get 'etc/shop' => 'home#shop'
  get 'etc/setting' => 'home#setting'
  
  get 'main' => 'home#main'
  get 'bag_item' => 'home#bag_item'
  get 'map' => 'home#map'
  get 'pet' => 'home#pet'
  get 'shop' => 'home#shop'
  get 'setting' => 'home#setting'
  
  

end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:category, :type_num, :name, :need_coin, :description, :coin_percent, :exp_percent, :other_percent)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :type_num %><br>
    <%= f.number_field :type_num %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :need_coin %><br>
    <%= f.number_field :need_coin %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :coin_percent %><br>
    <%= f.text_field :coin_percent %>
  </div>
  <div class="field">
    <%= f.label :exp_percent %><br>
    <%= f.text_field :exp_percent %>
  </div>
  <div class="field">
    <%= f.label :other_percent %><br>
    <%= f.text_field :other_percent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menus</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Type num</th>
      <th>Name</th>
      <th>Need coin</th>
      <th>Description</th>
      <th>Coin percent</th>
      <th>Exp percent</th>
      <th>Other percent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.category %></td>
        <td><%= menu.type_num %></td>
        <td><%= menu.name %></td>
        <td><%= menu.need_coin %></td>
        <td><%= menu.description %></td>
        <td><%= menu.coin_percent %></td>
        <td><%= menu.exp_percent %></td>
        <td><%= menu.other_percent %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @menu.category %>
</p>

<p>
  <strong>Type num:</strong>
  <%= @menu.type_num %>
</p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Need coin:</strong>
  <%= @menu.need_coin %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu.description %>
</p>

<p>
  <strong>Coin percent:</strong>
  <%= @menu.coin_percent %>
</p>

<p>
  <strong>Exp percent:</strong>
  <%= @menu.exp_percent %>
</p>

<p>
  <strong>Other percent:</strong>
  <%= @menu.other_percent %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>